# Development environment for anglerfish
name: anglerfish-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - bioconda::minimap2
  - pip
  - pip:
      - -e ".[dev]"
  - conda-forge::prettier
